GET http://localhost:5000/addresses/
Content-Type: application/json
###
GET http://localhost:5000/addresses/64981e4ceaa2cfe2d1aae77a
Content-Type: application/json
###
GET http://localhost:5000/addresses/user/64982471eaa2cfe2d1b32d58
Content-Type: application/json
###
GET http://localhost:5000/addresses/search/q?city=Tel%20Aviv
Content-Type: application/json
###
POST http://localhost:5000/addresses/
Content-Type: application/json

{
    "city": "São Paulo",
    "street": "Rua dos Bobos",
    "houseNum": "0",
    "postalCode": "0000"
}
###
PUT http://localhost:5000/addresses/64a167373859c30d168a232b
Content-Type: application/json

{
    "city": "Tel Aviv",
    "street": "Rua dos Bobos",
    "houseNum": "0",
    "postalCode": "0000",
    "user": "64982471eaa2cfe2d1b32d58"
}
###
DELETE http://localhost:5000/addresses/64a14c696490706095b7a2cd
Content-Type: application/json
###