POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "test1",
  "password": "test",
  "phoneNumber": "1234567890",
  "firstName": "test",
  "lastName": "test"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "test1",
  "password": "test"
}
###

GET http://localhost:5000/auth/check
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOTAzNjliODI2MjUzNjUyODIxNGYiLCJpYXQiOjE2ODkzNDczMTd9.9XltIwv2rgJn9TycsN-mPq0lt2xlOf2j5S5QucZhjUQ