POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "test1",
  "password": "test",
  "phoneNumber": "1234567890",
  "firstName": "test",
  "lastName": "test"
}
###
חולון,אהרון גלעדי, 23,0000
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "test1",
  "password": "test"
}
###

GET http://localhost:5000/auth/refresh
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NDNlZTZmNzk2YzRiYmNlNTAxOTUyMCIsImlhdCI6MTY4MjE3NDY3OCwiZXhwIjoxNjgyMTc0Njg4fQ.DLPMi65qPj2H9vmA3M4EwFcOHSRZZR_b110U1EnBRIg

###

GET http://localhost:5000/auth/verify
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NDNlZTZmNzk2YzRiYmNlNTAxOTUyMCIsImlhdCI6MTY4MjE3NDY3OCwiZXhwIjoxNjgyMTc0Njg4fQ.DLPMi65qPj2H9vmA3M4EwFcOHSRZZR_b110U1EnBRIg

###