GET http://localhost:5000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGE5N2NhZjZhZWQ3YTYxMTc1ZTJhMDQiLCJpYXQiOjE2ODg4MjkxODl9.ZJXodx9gDgt9CIsANhijl67fIDifWHIKnsSi6ak4hfY
Content-Type: application/json
###
GET http://localhost:5000/orders/649823c2eaa2cfe2d1b254bd
Content-Type: application/json
###
POST http://localhost:5000/api/orders/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGE5N2NhZjZhZWQ3YTYxMTc1ZTJhMDQiLCJpYXQiOjE2ODg4MjkxODl9.ZJXodx9gDgt9CIsANhijl67fIDifWHIKnsSi6ak4hfY
Content-Type: application/json

{
    "orderItems": [
        {
            "item": "64a31452148896f342568eb7",
            "quantity": 1
        }
    ],
    "totalPrice": 100,
    "deliveryMethod": "משלוח",
    "address": "הרצל 1, תל אביב",
    "paymentMethod": "אשראי"
}